<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SMT-LAP-053" ignored="0" name="Test" tests="2" failures="2" timestamp="26 Jan 2020 04:58:27 GMT" time="29.311" errors="0">
  <testcase name="GenericPEAPIMatchBackTestSet2" time="28.378" classname="com.smarteinc.api.tests.MatchBackTest">
    <failure type="java.lang.AssertionError" message="PE API script has failed">
      <![CDATA[java.lang.AssertionError: PE API script has failed
at com.smarteinc.api.tests.MatchBackTest.GenericPEAPIMatchBackTestSet2(MatchBackTest.java:226)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- GenericPEAPIMatchBackTestSet2 -->
  <testcase name="GenericPEAPIMatchBackTestSet1" time="29.218" classname="com.smarteinc.api.tests.MatchBackTest">
    <failure type="java.lang.AssertionError" message="PE API script has failed">
      <![CDATA[java.lang.AssertionError: PE API script has failed
at com.smarteinc.api.tests.MatchBackTest.GenericPEAPIMatchBackTestSet1(MatchBackTest.java:149)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- GenericPEAPIMatchBackTestSet1 -->
</testsuite> <!-- Test -->
